import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "../components/PageShell";

export const metadata: Metadata = { title: "List a game", description: "Submit an independent Manse game Site to the reviewed community Showcase." };

const checks = [
  "The game and manifest are public over HTTPS without a player login.",
  "The Site serves /.well-known/manse-game.json and its URLs match the deployment.",
  "The compatible engine and runtime assets are bundled with the Site.",
  "Source, license, accessibility disclosures, and asset provenance are present.",
  "You tested camera permission, simulator input, captions, and claimed devices.",
] as const;

export default function SubmitPage() {
  return <PageShell>
    <header className="submit-hero"><div className="shell submit-hero-grid"><div><p className="eyebrow eyebrow-coral">Community listing</p><h1>Publish there. Get discovered here.</h1><p>Your game stays on your own ChatGPT Site. The Manse Showcase stores only reviewed metadata and sends players directly to you.</p><div className="button-row"><a className="button button-coral button-large" href="#submit-flow">Start the checklist <span aria-hidden="true">↓</span></a><Link className="button button-ghost button-large" href="/docs#game-contract">Read the contract</Link></div></div><div className="ownership-card" aria-label="Ownership model">{[["01","Your source","Open repository"],["02","Your Site","Public game URL"],["03","Showcase","Reviewed link"]].map(([number,title,note], index) => <div key={number} className={`ownership-node ${index === 2 ? "highlight-node" : ""}`}><span>{number}</span><strong>{title}</strong><small>{note}</small></div>)}</div></div></header>
    <section className="submit-section section" id="submit-flow"><div className="shell submit-layout"><div className="submit-main"><p className="eyebrow">Before you submit</p><h2>A small contract keeps the catalog trustworthy.</h2><ol className="submission-checks">{checks.map((check,index) => <li key={check}><span>{String(index + 1).padStart(2,"0")}</span><p>{check}</p></li>)}</ol><div className="manifest-example"><div><span>Public manifest</span><b>Required</b></div><code>https://your-game.chatgpt.site/.well-known/manse-game.json</code><p>The build resolves this URL during review, validates it, and emits a static snapshot. Production never depends on a live third-party catalog request.</p></div></div><aside className="submit-aside"><p className="eyebrow">Fastest path</p><h2>Ask the plugin.</h2><p>In the Codex task that published your Site, say:</p><blockquote>“Submit this published game to the Manse Showcase.”</blockquote><p>Manse Creator verifies the deployment and prepares the catalog contribution. You review the diff before opening it.</p><a className="button button-ink button-full" href="https://github.com/ahndohun/manse" target="_blank" rel="noreferrer">Open repository <span aria-hidden="true">↗</span></a></aside></div></section>
    <section className="review-section section"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">What happens next</p><h2>Automation first. A human last.</h2></div><p>No central account, upload API, or publishing token. A normal open-source contribution is the entire submission system.</p></div><div className="review-flow">{[["01","Manifest resolves","CI confirms public HTTPS game and manifest URLs."],["02","Contract passes","Schema, compatibility, identity, URLs, license, access fields, and provenance."],["03","Maintainer reviews","A human checks semantic safety and whether disclosures match."],["04","Snapshot ships","Approved metadata joins the Showcase and links to the creator Site."]].map(([number,title,body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="boundary-section"><div className="shell boundary-grid"><div><p className="eyebrow eyebrow-light">Clear boundary</p><h2>Manse lists games. It does not host them.</h2></div><ul><li>The Showcase never proxies or iframes creator code.</li><li>Creators retain control of source, Site, and license.</li><li>Delisting removes discovery metadata, not the deployment.</li><li>Any compatible community can operate another Showcase.</li></ul></div></section>
    <section className="final-cta section"><div className="shell final-cta-card"><div><p className="eyebrow">Need a game first?</p><h2>Start with a sentence in Codex.</h2><p>Install Manse Creator and follow the workflow to a valid public Site.</p></div><div className="button-row"><Link className="button button-coral button-large" href="/docs#install">Install the plugin <span aria-hidden="true">↗</span></Link><Link className="button button-ghost button-large" href="/">Back to Showcase</Link></div></div></section>
  </PageShell>;
}
